return {
    SHEETS = {
        ["eggs-1.png"] = "rbxassetid://94145691660872",
        ["eggs-2.png"] = "rbxassetid://83315167540448",
        ["eggs-3.png"] = "rbxassetid://128599531000907",
    },
    EGG_SPRITES = {
        ["Boss Hunt Egg"] = { sheet = "eggs-1.png", x = 1, y = 1 },
        ["Duelists Egg"] = { sheet = "eggs-1.png", x = 1, y = 259 },
        ["Eggcited Egg"] = { sheet = "eggs-1.png", x = 1, y = 517 },
        ["Eggsploration Egg"] = { sheet = "eggs-1.png", x = 259, y = 1 },
        ["Falling Sky Egg"] = { sheet = "eggs-1.png", x = 517, y = 1 },
        ["Friendly Neighborhood Egg"] = { sheet = "eggs-1.png", x = 259, y = 259 },
        ["Night Hunter Egg"] = { sheet = "eggs-1.png", x = 259, y = 517 },
        ["Rocket Egg"] = { sheet = "eggs-1.png", x = 517, y = 259 },
        ["Thirsty Egg"] = { sheet = "eggs-1.png", x = 517, y = 517 },
        ["Firefly Egg"] = { sheet = "eggs-2.png", x = 1, y = 1 },
        ["Mended Egg"] = { sheet = "eggs-2.png", x = 1, y = 259 },
        ["Molten Egg"] = { sheet = "eggs-2.png", x = 1, y = 517 },
        ["Pirate Egg"] = { sheet = "eggs-2.png", x = 259, y = 1 },
        ["Sealed Showdown Egg"] = { sheet = "eggs-2.png", x = 517, y = 1 },
        ["Shockwave Egg"] = { sheet = "eggs-2.png", x = 259, y = 259 },
        ["Treasured Egg"] = { sheet = "eggs-2.png", x = 259, y = 517 },
        ["Wooden Egg"] = { sheet = "eggs-2.png", x = 517, y = 259 },
        ["Celestial Egg"] = { sheet = "eggs-3.png", x = 1, y = 1 },
        ["Eggspensive Egg"] = { sheet = "eggs-3.png", x = 1, y = 517 },
        ["Fishy Egg"] = { sheet = "eggs-3.png", x = 259, y = 1 },
        ["Full Moon Egg"] = { sheet = "eggs-3.png", x = 517, y = 1   },
        ["Gacha Egg"] = { sheet = "eggs-3.png", x = 259, y = 259 },
        ["Golden Egg"] = { sheet = "eggs-3.png", x = 259, y = 517 },
        ["Kawaii Egg"] = { sheet = "eggs-3.png", x = 517, y = 259 },
    },
    EGG_DESC = {
        ["Eggcited Egg"] = "Spawns at any location. The egg jumps in the opposite direction of the player.",
        ["Thirsty Egg"] = "Spawns at any location, needs to be dropped on water.",
        ["Rocket Egg"] = "Spawns at any location. The egg launchs itself in the opposite direction of the player.",
        ["Shockwave Egg"] = "Spawns at any location. The egg will knockback the player once before becoming collectable.",
        ["Fishy Egg"] = "Can be fished.",
        ["Wooden Egg"] = "Can be dropped after a tree falling.",
        ["Eggspensive Egg"] = "Can be found in the Blox Fruit Dealer's shop or the Permanent Fruit Shop hidden behind the icon of a random fruit.",
        ["Treasured Egg"] = "Can be dropped by collecting chests.",
        ["Duelists Egg"] = "Can be dropped from killing another player.",
        ["Mended Egg"] = "Spawns at any location separatedly. The player needs to find both red and blue parts.,
        ["Kawaii Egg"] = "Can be obtained with a chance by interacting with the Indra-chan portrait at Middle Town, Café, or Mansion.",
        ["Falling Sky Egg"] = "Spawns at any location, needs to be droped from a high place to be collected.",
        ["Eggsploration Egg"] = "Can spawn in the water after completing a sea event.",
        ["Friendly Neighborhood Egg"] = "Spawns at any location. The player needs to give the egg to the last Quest Giver unlocked in order to collect the egg.",
        ["Firefly Egg"] = "At a random location in the air, there will be a line of green and yellow dots. When all dots are collected, the egg will float in the air.",
        ["Pirate Egg"] = "Shows up on the loading screen randomly before you choose to spawns as a pirate or marine.",
        ["Molten Egg"] = "Spawns at any location, needs to be dropped on lava. Use flame raids if in third sea.",
        ["Boss Hunt Egg"] = "In the chat, a message will appear:Boss is holding a Boss Hunt Egg. Kill the boss and collect the egg.",
        ["Gacha Egg"] = "Can be rolled at gacha",
        ["Full Moon Egg"] = "Stare at the Full Moon when it's an egg to get it.",
        ["Night Hunter Egg"] = "Killing a boss during a Full Moon has a chance to transform it into a Werewolf which drops the egg.",
        ["Sealed Showdown Egg"] = "In the chat, a message will appear: "Sealed Showdown Egg has spawned on Location". The egg can be found there and have a cooldown to be collected.",
        ["Golden Egg"] = "Spawns at any location.",
        ["Celestial Egg"] = "Dropped from the boss after selecting "Secret" from the Easter Shop.",
    }
}
